const controller = require('./controller');
const express = require('express');
const {isAdmin} = require('../../../helpers/isAdmin');
const router = express.Router();
const { userBruteforce, sanitizeData } = require('../../../helpers/security');
const {auth}=require('../../middlewares/auth');
const { upload, uploadDocuments }=require('../../../helpers/multer');
router.post('/addProduct',sanitizeData,auth,isAdmin,controller.addProduct);
 router.get('/getProduct',sanitizeData,auth,isAdmin,controller.getProduct);
 router.put('/updateProduct/:id',sanitizeData,auth,isAdmin,controller.updateProduct);
 router.delete('/deleteProduct/:id',sanitizeData,auth,isAdmin,controller.deleteProduct);
 router.get('/getAllProducts',sanitizeData,auth,isAdmin,controller.getAllProducts);
 router.get('/sortByCategory/:category',sanitizeData,auth,isAdmin,controller.sortBycategory);
 router.get('/sortByName/:name',sanitizeData,auth,isAdmin,controller.sortByName);
 router.get('sortByPrice/:price',sanitizeData,auth,isAdmin,controller.sortByPrice);
 router.put('/addToWishlist/:id',sanitizeData,auth,controller.addToWishlist);
 router.get('/getWishlist',sanitizeData,auth,controller.getWishlist);
 router.delete('/deleteWishlist/:id',sanitizeData,auth,controller.deleteWishlist);
router.post('/upload',sanitizeData,auth,isAdmin, upload.single('image'), controller.uploadImage);
module.exports = router;